//        编译Less (gulp-less)
//        Autoprefixer (gulp-autoprefixer)
//        CSS压缩 (gulp-clean-css)
//        JS压缩 (gulp-uglify)
//        图片压缩 (gulp-imagemin)
//        JSHint (gulp-jshint)
//        合成 (gulp-concat)
//        重命名 (gulp-rename)
//        图片压缩 (gulp-imagemin)
//        即时重整(LiveReload) (gulp-livereload)
//        清理档案 (gulp-clean)
//        图片快取，只有更改过得图片会进行压缩 (gulp-cache)
//        更动通知 (gulp-notify)
npm install gulp-autoprefixer gulp-clean-css jshint gulp-jshint gulp-less gulp-concat gulp-uglify gulp-imagemin gulp-file-include gulp-html-beautify gulp-html-minify gulp-clean gulp-rename gulp-cache --save-dev